name: Analizar código y generar MD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/analisis/**'   # Evita loops al actualizar MD

jobs:
  analizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      
    steps:
  
      # Llamar Azure Function
      - name: Llamar Azure Function para análisis
        run: |
          curl -X POST "${{ secrets.AZURE_FUNCTION_URL }}" \
            -H "Content-Type: application/json" \
            -d "{\"repo\": \"${{ github.repository }}\", \"branch\": \"${{ github.ref_name }}\"}"
